padnt.index.title=padn't
padnt.index.description=The simplest way to share text online,Notepad but it's an online multiplayer app,Don't login - just use a URL,Don't pay - and no ads either!
padnt.index.placeholder=your-secret-page,my/online-notepad
padnt.index.github=https://github.com/baioc/padnt

spring.web.error.whitelabel.enabled=false
spring.web.error.path=/.error

spring.datasource.url=jdbc:h2:./database/padnt;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false

spring.main.banner-mode=off

server.compression.enabled=true
server.forward-headers-strategy=NATIVE

server.tomcat.basedir=logs/tomcat
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.max-days=180

logging.file.name=logs/padnt/root.log
logging.level.org.hibernate.SQL=info
